version: '3.4'

services:
  exercise.wwwapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "8082:8080"
    - "8083:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro