@exercise.wwwapi_HostAddress = http://localhost:5137

GET {{exercise.wwwapi_HostAddress}}/students/
Accept: application/json

###

GET {{exercise.wwwapi_HostAddress}}/students/
Accept: application/json



###

POST {{exercise.wwwapi_HostAddress}}/courses/
Content-Type: application/json

{
  "courseTitle": "Fullstack PHP",
  "startDate": "2024-01-04T08:00:00.000Z"
}

###

POST {{exercise.wwwapi_HostAddress}}/students/
Content-Type: application/json

{
  "firstName": "Stian",
  "lastName": "Gaustad",
  "dateOfBirth": "2000-08-05",
  "averageGrade": 3,
  "courseId": 3
}