// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.wwwapi.Data;

#nullable disable

namespace exercise.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240213144153_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            StudentCount = 0,
                            Title = "Not Specified"
                        },
                        new
                        {
                            Id = 1,
                            StudentCount = 0,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            StudentCount = 0,
                            Title = "Java"
                        },
                        new
                        {
                            Id = 3,
                            StudentCount = 0,
                            Title = "C"
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageGrade")
                        .HasColumnType("double precision")
                        .HasColumnName("average_grade");

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("course_date");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageGrade = 1.98,
                            CourseDate = new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2004, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mick",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 2,
                            AverageGrade = 8.0399999999999991,
                            CourseDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2000, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Donald",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 3,
                            AverageGrade = 7.2300000000000004,
                            CourseDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(1997, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elvis",
                            LastName = "Olsen"
                        },
                        new
                        {
                            Id = 4,
                            AverageGrade = 8.2400000000000002,
                            CourseDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2001, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 5,
                            AverageGrade = 6.5899999999999999,
                            CourseDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(1986, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 6,
                            AverageGrade = 9.6199999999999992,
                            CourseDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2006, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Audrey",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 7,
                            AverageGrade = 2.1200000000000001,
                            CourseDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(1981, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 8,
                            AverageGrade = 9.8900000000000006,
                            CourseDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2001, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mick",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 9,
                            AverageGrade = 0.68000000000000005,
                            CourseDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(1976, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 10,
                            AverageGrade = 7.9299999999999997,
                            CourseDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2006, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Oprah",
                            LastName = "Olsen"
                        },
                        new
                        {
                            Id = 11,
                            AverageGrade = 7.7000000000000002,
                            CourseDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(1983, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Elvis",
                            LastName = "Olsen"
                        },
                        new
                        {
                            Id = 12,
                            AverageGrade = 7.46,
                            CourseDate = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(2007, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emma",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 13,
                            AverageGrade = 8.7899999999999991,
                            CourseDate = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(1973, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Arthur",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 14,
                            AverageGrade = 6.79,
                            CourseDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(1979, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 15,
                            AverageGrade = 6.6900000000000004,
                            CourseDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2000, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Donald",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 16,
                            AverageGrade = 1.95,
                            CourseDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(1983, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Donald",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 17,
                            AverageGrade = 6.4400000000000004,
                            CourseDate = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(1983, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 18,
                            AverageGrade = 3.5600000000000001,
                            CourseDate = new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2002, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 19,
                            AverageGrade = 8.4000000000000004,
                            CourseDate = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(1988, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 20,
                            AverageGrade = 6.9000000000000004,
                            CourseDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(2001, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 21,
                            AverageGrade = 0.28000000000000003,
                            CourseDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(1990, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 22,
                            AverageGrade = 1.97,
                            CourseDate = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(1998, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emma",
                            LastName = "Jacobsen"
                        },
                        new
                        {
                            Id = 23,
                            AverageGrade = 4.6600000000000001,
                            CourseDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(1987, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Oprah",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 24,
                            AverageGrade = 6.4800000000000004,
                            CourseDate = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2003, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Audrey",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 25,
                            AverageGrade = 4.3700000000000001,
                            CourseDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 2,
                            DateOfBirth = new DateTime(2001, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Donald",
                            LastName = "Jacobsen"
                        },
                        new
                        {
                            Id = 26,
                            AverageGrade = 1.73,
                            CourseDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(1983, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Audrey",
                            LastName = "Jacobsen"
                        },
                        new
                        {
                            Id = 27,
                            AverageGrade = 2.6800000000000002,
                            CourseDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2004, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 28,
                            AverageGrade = 0.33000000000000002,
                            CourseDate = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 3,
                            DateOfBirth = new DateTime(1972, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mick",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 29,
                            AverageGrade = 3.0299999999999998,
                            CourseDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = 1,
                            DateOfBirth = new DateTime(2001, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emma",
                            LastName = "Hepburn"
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.HasOne("exercise.wwwapi.DataModels.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
