// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.wwwapi.Data;

#nullable disable

namespace exercise.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240209095520_Extension")]
    partial class Extension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_title");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseTitle = "Theater",
                            StartDate = "31-1-2024"
                        },
                        new
                        {
                            Id = 2,
                            CourseTitle = "Science",
                            StartDate = "28-1-2024"
                        },
                        new
                        {
                            Id = 3,
                            CourseTitle = "Piano",
                            StartDate = "2-2-2024"
                        },
                        new
                        {
                            Id = 4,
                            CourseTitle = "Chess",
                            StartDate = "5-2-2024"
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Registration", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<float>("AverageGrade")
                        .HasColumnType("real")
                        .HasColumnName("average_grade");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 4,
                            AverageGrade = 8.5f,
                            Id = 1
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            AverageGrade = 9.3f,
                            Id = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1,
                            AverageGrade = 8.8f,
                            Id = 3
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 2,
                            AverageGrade = 7.5f,
                            Id = 4
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2,
                            AverageGrade = 9.5f,
                            Id = 5
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3,
                            AverageGrade = 8.6f,
                            Id = 1
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = "18-4-2006",
                            FirstName = "Grigoris",
                            LastName = "Karampis"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = "15-4-2006",
                            FirstName = "Hannelieke",
                            LastName = "Hoogenboom"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = "3-4-2002",
                            FirstName = "Neomi",
                            LastName = "Bes"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = "22-10-2005",
                            FirstName = "Quinten",
                            LastName = "van Koeverden"
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Registration", b =>
                {
                    b.HasOne("exercise.wwwapi.DataModels.Course", "Course")
                        .WithMany("Registration")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exercise.wwwapi.DataModels.Student", "Student")
                        .WithMany("Registration")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Navigation("Registration");
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Navigation("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
