// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace exercise.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240212143810_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageGrade")
                        .HasColumnType("integer")
                        .HasColumnName("average_grade");

                    b.Property<string>("CourseStartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_start_date");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_title");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageGrade = 4,
                            CourseStartDate = "2024/01/08",
                            CourseTitle = "C# Academy",
                            DateOfBirth = "1998/11/29",
                            FirstName = "Henrik",
                            LastName = "Rosenkilde"
                        },
                        new
                        {
                            Id = 2,
                            AverageGrade = 5,
                            CourseStartDate = "2024/03/20",
                            CourseTitle = "Advanced Data Structures",
                            DateOfBirth = "1999/03/15",
                            FirstName = "Jens",
                            LastName = "Forgård"
                        },
                        new
                        {
                            Id = 3,
                            AverageGrade = 6,
                            CourseStartDate = "2024/04/10",
                            CourseTitle = "Machine Learning Fundamentals",
                            DateOfBirth = "1997/11/21",
                            FirstName = "Kristian",
                            LastName = "Verduin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
