// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.wwwapi.Data;

#nullable disable

namespace exercise.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240917123655_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_title");

                    b.Property<DateOnly>("StartDateForCourse")
                        .HasColumnType("date")
                        .HasColumnName("start_date_of_courses");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseTitle = "Maths",
                            StartDateForCourse = new DateOnly(2026, 5, 3)
                        },
                        new
                        {
                            Id = 2,
                            CourseTitle = "Science",
                            StartDateForCourse = new DateOnly(2030, 1, 18)
                        },
                        new
                        {
                            Id = 3,
                            CourseTitle = "Litterature",
                            StartDateForCourse = new DateOnly(2028, 2, 10)
                        },
                        new
                        {
                            Id = 4,
                            CourseTitle = "Arts and crafts",
                            StartDateForCourse = new DateOnly(2029, 1, 3)
                        },
                        new
                        {
                            Id = 5,
                            CourseTitle = "PE",
                            StartDateForCourse = new DateOnly(2030, 10, 29)
                        },
                        new
                        {
                            Id = 6,
                            CourseTitle = "Social sciences",
                            StartDateForCourse = new DateOnly(2026, 12, 24)
                        },
                        new
                        {
                            Id = 7,
                            CourseTitle = "Pyschology",
                            StartDateForCourse = new DateOnly(2030, 5, 31)
                        },
                        new
                        {
                            Id = 8,
                            CourseTitle = "Programming",
                            StartDateForCourse = new DateOnly(2026, 5, 2)
                        },
                        new
                        {
                            Id = 9,
                            CourseTitle = "Physics",
                            StartDateForCourse = new DateOnly(2028, 4, 28)
                        },
                        new
                        {
                            Id = 10,
                            CourseTitle = "History",
                            StartDateForCourse = new DateOnly(2023, 7, 24)
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageGrade")
                        .HasColumnType("integer")
                        .HasColumnName("average_grades");

                    b.Property<List<int>>("CourseIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("course_id's");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dates_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_names");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_names");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageGrade = 1,
                            CourseIds = new List<int> { 1, 10 },
                            DateOfBirth = new DateOnly(2026, 1, 24),
                            FirstName = "Ragnar",
                            LastName = "Mouse"
                        },
                        new
                        {
                            Id = 2,
                            AverageGrade = 1,
                            CourseIds = new List<int> { 2, 9 },
                            DateOfBirth = new DateOnly(2026, 12, 24),
                            FirstName = "Felix",
                            LastName = "Mouse"
                        },
                        new
                        {
                            Id = 3,
                            AverageGrade = 4,
                            CourseIds = new List<int> { 3, 8 },
                            DateOfBirth = new DateOnly(2022, 8, 27),
                            FirstName = "Barack",
                            LastName = "Mouse"
                        },
                        new
                        {
                            Id = 4,
                            AverageGrade = 4,
                            CourseIds = new List<int> { 4, 7 },
                            DateOfBirth = new DateOnly(2030, 7, 8),
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 5,
                            AverageGrade = 5,
                            CourseIds = new List<int> { 5, 6 },
                            DateOfBirth = new DateOnly(2024, 10, 22),
                            FirstName = "Neo",
                            LastName = "Lothbrok"
                        },
                        new
                        {
                            Id = 6,
                            AverageGrade = 1,
                            CourseIds = new List<int> { 6, 5 },
                            DateOfBirth = new DateOnly(2022, 5, 13),
                            FirstName = "Arnold",
                            LastName = "Mouse"
                        },
                        new
                        {
                            Id = 7,
                            AverageGrade = 2,
                            CourseIds = new List<int> { 7, 4 },
                            DateOfBirth = new DateOnly(2028, 1, 15),
                            FirstName = "Barack",
                            LastName = "Lothbrok"
                        },
                        new
                        {
                            Id = 8,
                            AverageGrade = 1,
                            CourseIds = new List<int> { 8, 3 },
                            DateOfBirth = new DateOnly(2025, 10, 15),
                            FirstName = "Arnold",
                            LastName = "Mathiasson"
                        },
                        new
                        {
                            Id = 9,
                            AverageGrade = 2,
                            CourseIds = new List<int> { 9, 2 },
                            DateOfBirth = new DateOnly(2025, 4, 12),
                            FirstName = "Neo",
                            LastName = "Sandler"
                        },
                        new
                        {
                            Id = 10,
                            AverageGrade = 1,
                            CourseIds = new List<int> { 10, 1 },
                            DateOfBirth = new DateOnly(2028, 1, 28),
                            FirstName = "Arnold",
                            LastName = "Andersson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
