// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.wwwapi.Data;

#nullable disable

namespace exercise.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgGrade")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_grade");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("StartOfCourse")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_of_course");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgGrade = 90.5,
                            CourseName = "Programming 101",
                            StartOfCourse = new DateTime(2023, 12, 16, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(5861)
                        },
                        new
                        {
                            Id = 2,
                            AvgGrade = 85.0,
                            CourseName = "Web Development Fundamentals",
                            StartOfCourse = new DateTime(2024, 2, 14, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(5872)
                        },
                        new
                        {
                            Id = 3,
                            AvgGrade = 88.200000000000003,
                            CourseName = "Data Structures and Algorithms",
                            StartOfCourse = new DateTime(2023, 10, 16, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(5882)
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_course_id");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 7, 8, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6150),
                            FirstName = "Minion1",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 2, 29, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6183),
                            FirstName = "Minion2",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 4, 28, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6201),
                            FirstName = "Minion3",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1825, 1, 15, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6219),
                            FirstName = "Minion4",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 6, 21, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6238),
                            FirstName = "Minion5",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 2, 22, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6257),
                            FirstName = "Minion6",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 10, 1, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6274),
                            FirstName = "Minion7",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 9, 14, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6292),
                            FirstName = "Minion8",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1825, 1, 30, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6309),
                            FirstName = "Minion9",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 8, 12, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6373),
                            FirstName = "Minion10",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 9, 27, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6391),
                            FirstName = "Minion11",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 5, 7, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6409),
                            FirstName = "Minion12",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 8, 5, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6426),
                            FirstName = "Minion13",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 5, 20, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6444),
                            FirstName = "Minion14",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 10, 26, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6461),
                            FirstName = "Minion15",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 5, 28, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6479),
                            FirstName = "Minion16",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 7, 13, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6495),
                            FirstName = "Minion17",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 8, 21, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6514),
                            FirstName = "Minion18",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 12, 12, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6530),
                            FirstName = "Minion19",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 8, 6, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6547),
                            FirstName = "Minion20",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 12, 6, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6564),
                            FirstName = "Minion21",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 4, 7, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6581),
                            FirstName = "Minion22",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 4, 28, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6597),
                            FirstName = "Minion23",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 2,
                            DateOfBirth = new DateTime(1824, 9, 15, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6614),
                            FirstName = "Minion24",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 4, 17, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6629),
                            FirstName = "Minion25",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 3, 14, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6644),
                            FirstName = "Minion26",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 5, 6, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6662),
                            FirstName = "Minion27",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1824, 9, 18, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6677),
                            FirstName = "Minion28",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 3,
                            DateOfBirth = new DateTime(1824, 4, 28, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6693),
                            FirstName = "Minion29",
                            LastName = "Banana"
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 1,
                            DateOfBirth = new DateTime(1825, 1, 13, 9, 59, 32, 754, DateTimeKind.Utc).AddTicks(6709),
                            FirstName = "Minion30",
                            LastName = "Banana"
                        });
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Student", b =>
                {
                    b.HasOne("exercise.wwwapi.DataModels.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("exercise.wwwapi.DataModels.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
